---
- name: Create and set permissions for /opt/data.txt
  hosts: app_servers
  become: yes
  tasks:
    - name: Create /opt/data.txt file
      file:
        path: /opt/data.txt
        state: touch
        mode: "0644"

    - name: Set ownership of /opt/data.txt on stapp01
      ansible.builtin.file:
        path: /opt/data.txt
        owner: tony
        group: tony
      when: inventory_hostname == "stapp01"

    - name: Set ownership of /opt/data.txt on stapp02
      ansible.builtin.file:
        path: /opt/data.txt
        owner: steve
        group: steve
      when: inventory_hostname == "stapp02"

    - name: Set ownership of /opt/data.txt on stapp03
      ansible.builtin.file:
        path: /opt/data.txt
        owner: banner
        group: banner
      when: inventory_hostname == "stapp03"